### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by lorenzwalthert** [falling-fruit/fruitr#1]
Seems to be a cool pacakge. However, I was not able to find the licence of the package. What is the licence the package is distributed under?

**Comment by lorenzwalthert** [comment]
If it is one of the standard licences, you can use devtools to add it:
```r
devtools::use_mit_license() #or 
devtools::use_gpl3_license()
```

**Comment by ezwelty** [comment]
Great question, @lorenzwalthert ! Since the rest of Falling Fruit's code is currently under GPL3, I've set that here are well.

**Comment by lorenzwalthert** [comment]
Cool, thanks for the quick response.
